### ISSUE TITLE
Disable default colors if not set

### ISSUE THREAD

**Issue by voidit** [seiyable/vue-simple-svg#4]
It would be very helpful to disable color setting completely if nothing was sent as a parameter.
For example, if I use multicolored graphics, it will save some juices just to leave it alone instead of redefining styles from scratch after SVG had been loaded.
For example, if I place an element like so:
`        <simple-svg
                :filepath="'/PATH_/TO_/YOUR_/FILE.svg'"
                :width="'400px'"
                :height="'400px'"
                :id="'custom-id'"
                @ready="onSvgReady()"
        />`
It should not touch existing styles.

**Comment by seiyable** [comment]
I disabled default parameters and this should solve the issues.
[](https://github.com/seiyable/vue-simple-svg/commit/4d18474d2678695d2333b31400cedc3cb7a89d3a)

**Comment by CelticParser** [comment]
Hi, this stil strips the svg's colors and defaults to black.

**Comment by ayyoubjadoo** [comment]
Hi,
Also setting the `fill` and `stroke` props to `none` doesn't work, it's not drawing black but its still discarding the original fill and stroke styles in the svg itself.

Nice plugin BTW and this issue must be fixed to make it perfect.
